blank_issues_enabled: false
contact_links:
  - name: Bugs, Feature Requests, Ideas
    url: https://github.com/hasura/graphql-engine/issues/new/choose
    about: Use hasura/graphql-engine for issues related to ndc-hub.
  - name: â˜ï¸ Hasura Cloud Help & Support Center
    url: https://cloud.hasura.io/support
    about: For Issues related to Hasura Cloud and DDN âš¡ï¸
  - name: â“ Get Support from Discord Community
    url: https://discord.com/invite/hasura
    about: Please ask and answer questions here. ğŸ¥
  - name: ğŸ™‹â€â™€ï¸ Have a question on how to achieve something with Hasura?
    url: https://github.com/hasura/graphql-engine/discussions
    about: Start a GitHub discussion
